### ISSUE TITLE
Dashboard connectivity issues on Azure

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/garden-setup#19]
When the Gardener is deployed on Azure, the dashboard sometimes doesn't work properly.

Dashboard logs show something like this:
```
2019-04-16T11:11:12.924Z - debug: watch closed 4000 Client network socket disconnected before secure TLS connection was established
2019-04-16T11:11:12.923Z - error: watch projects disconnected { Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: undefined,
  host: 'api.ingress.mycluster.org',
  port: 443,
  localAddress: undefined }
```

The problem will disappear/reappear from time to time. 
Everything else seems to work fine.

**Comment by Diaphteiros** [comment]
Haven't seen this for a while, closing the issue and re-opening if it appears again.
